import {
    LayoutDashboard,
    Package,
    Warehouse,
    BarChart2,
    Users,
    Truck,
    Settings,
    ClipboardList,
    MapPin,
    Contact,
    ArrowRightLeft,
} from 'lucide-react';

export const getNavLinks = (t, can) => [
    {
        name: t('ui.dashboard'),
        href: route('dashboard'),
        icon: LayoutDashboard,
        current: route().current('dashboard'),
        show: can.view_dashboard,
    },
    {
        name: t('ui.product'),
        href: route('products.index'),
        icon: Package,
        current: route().current('products.*'),
        show: can.view_products,
    },
    {
        name: t('ui.locations'),
        href: route('locations.index'),
        icon: MapPin,
        current: route().current('locations.*'),
        show: can.view_locations,
    },
    {
        name: t('ui.stock'),
        href: route('stock.index'),
        icon: Warehouse,
        current:
            route().current('stock.*') && !route().current('stock-movements.*'),
        show: can.view_inventory,
    },
    {
        name: t('ui.stock_movements'),
        href: route('stock-movements.index'),
        icon: ArrowRightLeft,
        current: route().current('stock-movements.*'),
        show: can.view_stock_movements,
    },
    {
        name: t('ui.transactions'),
        href: route('transactions.index'),
        icon: ClipboardList,
        current: route().current('transactions.*'),
        show: can.view_transactions,
    },
    {
        name: t('ui.suppliers'),
        href: route('suppliers.index'),
        icon: Truck,
        current: route().current('suppliers.*'),
        show: can.view_suppliers,
    },
    {
        name: t('ui.customers'),
        href: route('customers.index'),
        icon: Contact,
        current: route().current('customers.*'),
        show: can.view_customers,
    },
    {
        name: t('ui.reports'),
        href: route('reports.index'),
        icon: BarChart2,
        current: route().current('reports.*'),
        show: can.view_reports,
    },
    {
        name: t('ui.users'),
        href: route('users.index'),
        icon: Users,
        current: route().current('users.*'),
        show: can.manage_system,
    },
    {
        name: t('ui.types'),
        href: route('types.index'),
        icon: Settings,
        current: route().current('types.*'),
        show: can.manage_system,
    },
];
