export const ROUTES = {
    DASHBOARD: 'dashboard',
    LOGIN: 'login',
    LOGOUT: 'logout',
    REGISTER: 'register',
    SETUP_INDEX: 'setup.index',
    SETUP_STORE: 'setup.store',
    LOCALE_UPDATE: 'locale.update',
    REPORTS_INDEX: 'reports.index',
    NOTIFICATIONS: {
        INDEX: 'notifications.index',
        API: 'notifications.api',
        READ: 'notifications.read',
        READ_ALL: 'notifications.readAll',
    },
    PROFILE: {
        EDIT: 'profile.edit',
        UPDATE: 'profile.update',
        DESTROY: 'profile.destroy',
    },
    PASSWORD: {
        UPDATE: 'password.update',
    },
    USERS: {
        INDEX: 'users.index',
        CREATE: 'users.create',
        STORE: 'users.store',
        EDIT: 'users.edit',
        UPDATE: 'users.update',
        DESTROY: 'users.destroy',
        RESTORE: 'users.restore',
    },
    TYPES: {
        INDEX: 'types.index',
        CREATE: 'types.create',
        STORE: 'types.store',
        EDIT: 'types.edit',
        UPDATE: 'types.update',
        DESTROY: 'types.destroy',
        RESTORE: 'types.restore',
    },
    LOCATIONS: {
        INDEX: 'locations.index',
        CREATE: 'locations.create',
        STORE: 'locations.store',
        EDIT: 'locations.edit',
        UPDATE: 'locations.update',
        DESTROY: 'locations.destroy',
        RESTORE: 'locations.restore',
    },
    CUSTOMERS: {
        INDEX: 'customers.index',
        CREATE: 'customers.create',
        STORE: 'customers.store',
        EDIT: 'customers.edit',
        UPDATE: 'customers.update',
        DESTROY: 'customers.destroy',
        RESTORE: 'customers.restore',
    },
    SUPPLIERS: {
        INDEX: 'suppliers.index',
        CREATE: 'suppliers.create',
        STORE: 'suppliers.store',
        EDIT: 'suppliers.edit',
        UPDATE: 'suppliers.update',
        DESTROY: 'suppliers.destroy',
        RESTORE: 'suppliers.restore',
    },
    PRODUCTS: {
        INDEX: 'products.index',
        CREATE: 'products.create',
        STORE: 'products.store',
        EDIT: 'products.edit',
        UPDATE: 'products.update',
        DESTROY: 'products.destroy',
        RESTORE: 'products.restore',
        SEARCH: 'api.products.search',
    },
    STOCK: {
        INDEX: 'stock.index',
        SHOW: 'stock.show',
        ADJUST_FORM: 'stock.adjust.form',
        ADJUST: 'stock.adjust',
        API_QUANTITY: 'api.inventory.quantity',
    },
    STOCK_MOVEMENTS: {
        INDEX: 'stock-movements.index',
    },
    TRANSACTIONS: {
        INDEX: 'transactions.index',
        PURCHASES: {
            CREATE: 'transactions.purchases.create',
            STORE: 'transactions.purchases.store',
            SHOW: 'transactions.purchases.show',
            APPROVE: 'transactions.purchases.approve',
            REJECT: 'transactions.purchases.reject',
            SHIP: 'transactions.purchases.ship',
            RECEIVE: 'transactions.purchases.receive',
        },
        SELLS: {
            CREATE: 'transactions.sells.create',
            STORE: 'transactions.sells.store',
            SHOW: 'transactions.sells.show',
            APPROVE: 'transactions.sells.approve',
            REJECT: 'transactions.sells.reject',
            SHIP: 'transactions.sells.ship',
            RECEIVE: 'transactions.sells.receive',
        },
        TRANSFERS: {
            CREATE: 'transactions.transfers.create',
            STORE: 'transactions.transfers.store',
            SHOW: 'transactions.transfers.show',
            APPROVE: 'transactions.transfers.approve',
            REJECT: 'transactions.transfers.reject',
            SHIP: 'transactions.transfers.ship',
            RECEIVE: 'transactions.transfers.receive',
        },
    },
    CART: {
        PURCHASE: {
            STORE: 'purchase.cart.store',
            UPDATE: 'purchase.cart.update',
            DESTROY_ALL: 'purchase.cart.destroy.all',
            DESTROY_SUPPLIER: 'purchase.cart.destroy.supplier',
            DESTROY_ITEM: 'purchase.cart.destroy.item',
        },
        SELL: {
            STORE: 'sell.cart.store',
            UPDATE_PRICES: 'sell.cart.update-prices',
            UPDATE: 'sell.cart.update',
            DESTROY_LOCATION: 'sell.cart.destroy.location',
            DESTROY_ITEM: 'sell.cart.destroy.item',
        },
    },
    PAYMENT: {
        SELL_SNAP: 'payment.sell.snap',
        PURCHASE_SNAP: 'payment.purchase.snap',
        INSTALLMENT_SNAP: 'payment.installment.snap',
        VERIFY: 'payment.verify',
        STATUS: 'payment.status',
        INSTALLMENTS_PAY: 'installments.pay',
    },
} as const;
